import os

from dotenv import load_dotenv

load_dotenv()

TRANSCRIPTION_PROVIDER = os.getenv("TRANSCRIPTION_PROVIDER", "deepgram")
EXPLANATION_PROVIDER = os.getenv("EXPLANATION_PROVIDER", "gemini")

DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
GEMINI_TIMEOUT_SECONDS = float(os.getenv("GEMINI_TIMEOUT_SECONDS", "4.0"))
GEMINI_CONTEXT_LINES = int(os.getenv("GEMINI_CONTEXT_LINES", "4"))
GEMINI_CONFIDENCE_THRESHOLD = float(os.getenv("GEMINI_CONFIDENCE_THRESHOLD", "0.67"))
GEMINI_TERM_COOLDOWN_SECONDS = int(os.getenv("GEMINI_TERM_COOLDOWN_SECONDS", "45"))
GEMINI_MIN_REQUEST_SECONDS = float(os.getenv("GEMINI_MIN_REQUEST_SECONDS", "6.5"))
GEMINI_MAX_RETRIES = int(os.getenv("GEMINI_MAX_RETRIES", "3"))
GEMINI_RETRY_BASE_SECONDS = float(os.getenv("GEMINI_RETRY_BASE_SECONDS", "0.2"))

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_REALTIME_SESSION_MODEL = os.getenv("OPENAI_REALTIME_SESSION_MODEL", "gpt-realtime")
OPENAI_REALTIME_MODEL = os.getenv("OPENAI_REALTIME_MODEL", "gpt-4o-mini-transcribe")
OPENAI_REALTIME_LANGUAGE = os.getenv("OPENAI_REALTIME_LANGUAGE", "es")
OPENAI_REALTIME_PROMPT = os.getenv(
    "OPENAI_REALTIME_PROMPT",
    "",
)
OPENAI_REALTIME_DICTIONARY_TERMS = int(
    os.getenv("OPENAI_REALTIME_DICTIONARY_TERMS", "80")
)
OPENAI_REALTIME_VAD_THRESHOLD = float(os.getenv("OPENAI_REALTIME_VAD_THRESHOLD", "0.62"))
OPENAI_REALTIME_PREFIX_PADDING_MS = int(
    os.getenv("OPENAI_REALTIME_PREFIX_PADDING_MS", "180")
)
OPENAI_REALTIME_SILENCE_MS = int(os.getenv("OPENAI_REALTIME_SILENCE_MS", "320"))
OPENAI_REALTIME_VAD_MODE = os.getenv("OPENAI_REALTIME_VAD_MODE", "server_vad")
OPENAI_REALTIME_VAD_EAGERNESS = os.getenv("OPENAI_REALTIME_VAD_EAGERNESS", "high")
OPENAI_REALTIME_CREATE_RESPONSE = os.getenv("OPENAI_REALTIME_CREATE_RESPONSE", "false").lower() == "true"
OPENAI_REALTIME_OPTIMISTIC_FINAL_MS = int(
    os.getenv("OPENAI_REALTIME_OPTIMISTIC_FINAL_MS", "420")
)
OPENAI_TEXT_MODEL = os.getenv("OPENAI_TEXT_MODEL", "gpt-4.1-mini")
OPENAI_TEXT_TIMEOUT_SECONDS = float(os.getenv("OPENAI_TEXT_TIMEOUT_SECONDS", "4.0"))
OPENAI_MIN_REQUEST_SECONDS = float(os.getenv("OPENAI_MIN_REQUEST_SECONDS", "1.5"))
ALLOWED_TRANSCRIPT_SCRIPTS = {
    part.strip().upper()
    for part in os.getenv("ALLOWED_TRANSCRIPT_SCRIPTS", "LATIN").split(",")
    if part.strip()
}

DEEPGRAM_AUDIO_RATE = 16000
DEEPGRAM_AUDIO_CHUNK = 4096
OPENAI_AUDIO_RATE = 24000
OPENAI_AUDIO_CHUNK = 2400
