import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(dotenv_path=Path(__file__).resolve().parent / ".env", override=True)


def _optional_int(name: str) -> int | None:
    value = os.getenv(name, "").strip()
    if not value:
        return None
    return int(value)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_REALTIME_SESSION_MODEL = os.getenv(
    "OPENAI_REALTIME_SESSION_MODEL", "gpt-realtime"
)
OPENAI_REALTIME_MODEL = os.getenv("OPENAI_REALTIME_MODEL", "gpt-4o-transcribe")
OPENAI_REALTIME_LANGUAGE = os.getenv("OPENAI_REALTIME_LANGUAGE", "es")
OPENAI_REALTIME_TRANSCRIPTION_PROMPT = os.getenv(
    "OPENAI_REALTIME_TRANSCRIPTION_PROMPT", ""
)
OPENAI_REALTIME_HINT_TERMS = int(os.getenv("OPENAI_REALTIME_HINT_TERMS", "0"))
OPENAI_REALTIME_MIN_AVG_LOGPROB = float(
    os.getenv("OPENAI_REALTIME_MIN_AVG_LOGPROB", "-1.6")
)
OPENAI_REALTIME_VAD_THRESHOLD = float(
    os.getenv("OPENAI_REALTIME_VAD_THRESHOLD", "0.52")
)
OPENAI_REALTIME_PREFIX_PADDING_MS = int(
    os.getenv("OPENAI_REALTIME_PREFIX_PADDING_MS", "220")
)
OPENAI_REALTIME_SILENCE_MS = int(os.getenv("OPENAI_REALTIME_SILENCE_MS", "420"))
OPENAI_REALTIME_VAD_MODE = os.getenv("OPENAI_REALTIME_VAD_MODE", "server_vad")
OPENAI_REALTIME_VAD_EAGERNESS = os.getenv("OPENAI_REALTIME_VAD_EAGERNESS", "high")
OPENAI_REALTIME_CREATE_RESPONSE = (
    os.getenv("OPENAI_REALTIME_CREATE_RESPONSE", "false").lower() == "true"
)
OPENAI_REALTIME_PROTOCOL = os.getenv("OPENAI_REALTIME_PROTOCOL", "auto").strip().lower()
OPENAI_REALTIME_OPTIMISTIC_FINAL_MS = int(
    os.getenv("OPENAI_REALTIME_OPTIMISTIC_FINAL_MS", "0")
)
OPENAI_EXPLANATION_MODEL = os.getenv("OPENAI_EXPLANATION_MODEL", "gpt-4.1-mini")
OPENAI_EXPLANATION_TIMEOUT_SECONDS = float(
    os.getenv("OPENAI_EXPLANATION_TIMEOUT_SECONDS", "4.0")
)
OPENAI_EXPLANATION_CONTEXT_LINES = int(
    os.getenv("OPENAI_EXPLANATION_CONTEXT_LINES", "4")
)
OPENAI_EXPLANATION_CONFIDENCE_THRESHOLD = float(
    os.getenv("OPENAI_EXPLANATION_CONFIDENCE_THRESHOLD", "0.67")
)
OPENAI_EXPLANATION_TERM_COOLDOWN_SECONDS = int(
    os.getenv("OPENAI_EXPLANATION_TERM_COOLDOWN_SECONDS", "45")
)
OPENAI_EXPLANATION_MIN_REQUEST_SECONDS = float(
    os.getenv("OPENAI_EXPLANATION_MIN_REQUEST_SECONDS", "1.5")
)
OPENAI_EXPLANATION_MAX_RETRIES = int(os.getenv("OPENAI_EXPLANATION_MAX_RETRIES", "3"))
OPENAI_EXPLANATION_RETRY_BASE_SECONDS = float(
    os.getenv("OPENAI_EXPLANATION_RETRY_BASE_SECONDS", "0.2")
)
ALLOWED_TRANSCRIPT_SCRIPTS = {
    part.strip().upper()
    for part in os.getenv("ALLOWED_TRANSCRIPT_SCRIPTS", "LATIN").split(",")
    if part.strip()
}
AUDIO_INPUT_DEVICE_INDEX = _optional_int("AUDIO_INPUT_DEVICE_INDEX")
AUDIO_INPUT_DEVICE_NAME = os.getenv("AUDIO_INPUT_DEVICE_NAME", "").strip()

OPENAI_AUDIO_RATE = 24000
OPENAI_AUDIO_CHUNK = 2400
